/**
 * HTTP Basic authentication for the internal site.
 *
 * `internal/` is the knowledge plane — PRDs, gap notes, approved house rules. It
 * is not public content, and this file is the only thing standing between it and
 * the open web: Vercel's own Deployment Protection is a paid feature on this
 * account, so the gate has to live in the project.
 *
 * Vercel looks for `middleware.ts` at the root of the project — the same level
 * as `package.json`, which for this project is `sites/internal/` (its configured
 * Root Directory). It runs before the CDN cache on every request, so the static
 * build output in `public/` is covered too, not just HTML routes. No `config`
 * matcher is exported on purpose: the default is *every* route, and an allowlist
 * that has to be kept in sync with the build output is exactly the kind of thing
 * that quietly stops covering a new path. The one exception, `/robots.txt`, is a
 * conditional inside the handler instead.
 *
 * Runtime is Edge (the default for this file convention), which is why nothing
 * here is imported: no `node:crypto`, no `next/server`, no `@vercel/functions`.
 */

const REALM = "docloop internal"

/**
 * Served to everyone, unauthenticated. A crawler that only ever sees a 401
 * learns nothing about whether it may index the URL, and some index it anyway;
 * a reachable `Disallow: /` is the instruction that actually gets obeyed. It is
 * emitted from here rather than shipped as a file because this site's served
 * tree (`public/`) is generated by vendored Quartz from `content/`, and both are
 * gitignored build artifacts — there is no committed directory to put it in.
 */
const ROBOTS_TXT = "User-agent: *\nDisallow: /\n"

/**
 * Compares two strings in time that does not depend on *where* they differ —
 * no early return on the first differing byte, which would let an attacker
 * recover the password one character at a time from response latency.
 *
 * A length mismatch does return early: that leaks only the length, which is not
 * the secret, and there is no way to compare unequal-length inputs without
 * either padding or leaking it anyway. `crypto.timingSafeEqual` is not used
 * because it is Node-only and this runs on the Edge runtime.
 *
 * Comparison is over UTF-16 code units rather than encoded bytes: `atob` yields
 * latin1 code units and the expected values arrive as plain JS strings, so
 * comparing code units directly avoids an encoding round-trip in the middle of
 * a security check.
 */
function constantTimeEquals(a: string, b: string): boolean {
  if (a.length !== b.length) return false
  let diff = 0
  for (let i = 0; i < a.length; i++) {
    diff |= a.charCodeAt(i) ^ b.charCodeAt(i)
  }
  return diff === 0
}

/** Parses `Authorization: Basic <base64>`. Anything malformed reads as "no credentials". */
function decodeBasicCredentials(header: string | null): { user: string; password: string } | null {
  if (!header) return null

  const space = header.indexOf(" ")
  if (space < 0) return null
  if (header.slice(0, space).toLowerCase() !== "basic") return null

  let decoded: string
  try {
    decoded = atob(header.slice(space + 1).trim())
  } catch {
    // `atob` throws on invalid base64. A garbled header must produce a 401, not
    // an unhandled exception — a 500 here is a broken gate, not a closed one.
    return null
  }

  // Only the first colon separates the two fields; a password may contain more.
  const colon = decoded.indexOf(":")
  if (colon < 0) return null
  return { user: decoded.slice(0, colon), password: decoded.slice(colon + 1) }
}

export default function middleware(request: Request): Response | undefined {
  const { pathname } = new URL(request.url)

  if (pathname === "/robots.txt") {
    return new Response(ROBOTS_TXT, {
      status: 200,
      headers: { "content-type": "text/plain; charset=utf-8" },
    })
  }

  const expectedUser = process.env.INTERNAL_SITE_USER
  const expectedPassword = process.env.INTERNAL_SITE_PASSWORD

  // Fail closed. An unset credential is a misconfiguration, and the safe reading
  // of a misconfigured gate on an internal tree is "serve nothing" — never "let
  // everyone in", which is what falling through would mean. 503 rather than 401
  // so the failure is legible as ours: no credential the caller could supply
  // would help, and no amount of retrying will change the answer.
  if (!expectedUser || !expectedPassword) {
    return new Response(
      "This site is misconfigured: access credentials are not set. No content is being served.\n",
      {
        status: 503,
        headers: { "content-type": "text/plain; charset=utf-8", "cache-control": "no-store" },
      },
    )
  }

  const supplied = decodeBasicCredentials(request.headers.get("authorization"))

  let authorized = false
  if (supplied) {
    // Both comparisons are evaluated before they are combined. Using `&&`
    // directly on the calls would short-circuit, and skipping the password
    // compare on a wrong username leaks — via timing — which usernames exist.
    const userMatches = constantTimeEquals(supplied.user, expectedUser)
    const passwordMatches = constantTimeEquals(supplied.password, expectedPassword)
    authorized = userMatches && passwordMatches
  }

  if (!authorized) {
    return new Response("Authentication required.\n", {
      status: 401,
      headers: {
        // Prompts a browser for credentials instead of showing a bare error.
        "www-authenticate": `Basic realm="${REALM}", charset="UTF-8"`,
        "content-type": "text/plain; charset=utf-8",
        // Never let a CDN or browser cache the refusal — or the grant.
        "cache-control": "no-store",
      },
    })
  }

  // Authenticated: return nothing, and the request continues to the static
  // build output as if this middleware were not here.
  return undefined
}
